services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"  # Map local port 5432 to the container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data across restarts

volumes:
  postgres_data: